module NewsBufferApp {
    interface NewsBuffer {
        boolean put(in string noticiaXML);
        boolean get(out string noticiaXML);
        boolean read(out string noticiaXML);
        boolean isEmpty();
        long getCount();
        long getLimit();
        void fijarLimiteNoticias(in long numero_maximo);
        oneway void shutdown();
    };
};
