services:
  eureka-server:
    image: ghcr.io/aek676/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

  omdb-service:
    image: ghcr.io/aek676/omdb-service:latest
    container_name: omdb-service
    # ports:
    #   - "8085:8085"
    environment:
      # - SERVER_PORT=8085
      - EUREKA_INSTANCE_HOSTNAME=omdb-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - OMDB_API_KEY=${OMDB_API_KEY}
    depends_on:
      - eureka-server

  tmdb-service:
    image: ghcr.io/aek676/tmdb-service:latest
    container_name: tmdb-service
    # ports:
    #   - "8086:8086"
    environment:
      # - SERVER_PORT=8086
      - EUREKA_INSTANCE_HOSTNAME=tmdb-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - eureka-server

  movies-manager:
    image: ghcr.io/aek676/movies-manager:latest
    container_name: movies-manager
    # ports:
    #   - "8087:8087"
    environment:
      # - SERVER_PORT=8087
      - EUREKA_INSTANCE_HOSTNAME=movies-manager
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - omdb-service
      - tmdb-service

  gateway:
    image: ghcr.io/aek676/gateway:latest
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - omdb-service
      - tmdb-service
      - movies-manager
