services:
  eureka-server:
    image: eureka.server:0.0.1-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8761:8761"

  omdb-service:
    image: eureka.client.omdb:0.0.1-SNAPSHOT
    container_name: omdb-service
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - EUREKA_INSTANCE_HOSTNAME=omdb-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - OMDB_API_KEY=${OMDB_API_KEY}
    depends_on:
      - eureka-server

  tmdb-service:
    image: eureka.client.tmdb:0.0.1-SNAPSHOT
    container_name: tmdb-service
    ports:
      - "8086:8086"
    environment:
      - SERVER_PORT=8086
      - EUREKA_INSTANCE_HOSTNAME=tmdb-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - eureka-server

  movies-manager:
    image: eureka.client.movies-manager:0.0.1-SNAPSHOT
    container_name: movies-manager
    ports:
      - "8087:8087"
    environment:
      - SERVER_PORT=8087
      - EUREKA_INSTANCE_HOSTNAME=movies-manager
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - omdb-service
      - tmdb-service

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_INSTANCE_HOSTNAME=gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - omdb-service
      - tmdb-service
      - movies-manager
