package NewsBufferApp;


/**
* NewsBufferApp/NewsBufferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/NewsBuffer.idl
* Friday, March 20, 2026 8:54:21 PM CET
*/

public interface NewsBufferOperations 
{
  boolean put (String noticiaXML);
  boolean get (org.omg.CORBA.StringHolder noticiaXML);
  boolean read (org.omg.CORBA.StringHolder noticiaXML);
  boolean isEmpty ();
  int getCount ();
  void shutdown ();
} // interface NewsBufferOperations
