package NewsBufferApp;


/**
* NewsBufferApp/NewsBuffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/NewsBuffer.idl
* Friday, March 20, 2026 8:54:21 PM CET
*/

public interface NewsBuffer extends NewsBufferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NewsBuffer
