package NewsBufferApp;

/**
* NewsBufferApp/NewsBufferHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/NewsBuffer.idl
* Saturday, March 21, 2026 2:33:56 PM CET
*/

public final class NewsBufferHolder implements org.omg.CORBA.portable.Streamable
{
  public NewsBufferApp.NewsBuffer value = null;

  public NewsBufferHolder ()
  {
  }

  public NewsBufferHolder (NewsBufferApp.NewsBuffer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NewsBufferApp.NewsBufferHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NewsBufferApp.NewsBufferHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NewsBufferApp.NewsBufferHelper.type ();
  }

}
