package NewsBufferApp;


/**
* NewsBufferApp/NewsBufferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/NewsBuffer.idl
* Saturday, March 21, 2026 2:33:56 PM CET
*/

public interface NewsBufferOperations 
{
  boolean put (String noticiaXML);
  boolean get (org.omg.CORBA.StringHolder noticiaXML);
  boolean read (org.omg.CORBA.StringHolder noticiaXML);
  boolean isEmpty ();
  int getCount ();
  int getLimit ();
  void fijarLimiteNoticias (int numero_maximo);
  void shutdown ();
} // interface NewsBufferOperations
