package NewsBufferApp;


/**
* NewsBufferApp/NewsBuffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/NewsBuffer.idl
* Saturday, March 21, 2026 2:33:56 PM CET
*/

public interface NewsBuffer extends NewsBufferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NewsBuffer
