# Configuration for manager-students
server.port=8082

# Database configuration (JPA)
spring.datasource.url=jdbc:postgresql://localhost:5433/dwsc_students
spring.datasource.username=estudiante
spring.datasource.password=estudiante
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# OpenAPI Info
springdoc.api-info.title=Manager Students API
springdoc.api-info.description=API for managing students (JPA)
springdoc.api-info.version=1.0.0
springdoc.api-info.contact.name=UAL Team
springdoc.api-info.contact.email=anass@ual.es
