# Configuration for manager-students
server.port=8082

# Database configuration (JPA)
spring.datasource.url=jdbc:postgresql://localhost:5433/dwsc_students
spring.datasource.username=estudiante
spring.datasource.password=estudiante
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update