spring.application.name=actividad5-jpa

spring.datasource.url=jdbc:postgresql://localhost:5432/dwsc
spring.datasource.username=${DB_USERNAME:estudiante}
spring.datasource.password=${DB_PASSWORD:estudiante}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
